export const navigationLinks = [
    { name: "Dashboard", link: false, border: false },
    {
        name: "Dashboard",
        link: true,
        border: false,
        startWith: "/admin/dashboard",
        route: "admin.dashboard",
        icon: "ChartPieIcon",
    },
    { name: "Inventory", link: false, border: false },
    // {
    //     name: "Categories",
    //     link: true,
    //     border: false,
    //     startWith: "/admin/categories",
    //     route: "admin.categories.index",
    //     icon: "Squares2X2Icon",
    // },
    {
        name: "Services",
        link: true,
        border: false,
        startWith: "/admin/services",
        route: "admin.services.index",
        icon: "Square2StackIcon",
    },
    {
        name: "Repair Types",
        link: true,
        border: false,
        startWith: "/admin/repair-types",
        route: "admin.repair-types.index",
        icon: "WrenchIcon",
    },
    { name: "Other", link: false, border: true },
    // {
    //     name: "Reviews",
    //     link: true,
    //     border: false,
    //     startWith: "/admin/reviews",
    //     route: "admin.reviews.index",
    //     icon: "StarIcon",
    // },
    {
        name: "Inquiries",
        link: true,
        border: false,
        startWith: "/admin/inquiries",
        route: "admin.inquiries.index",
        icon: "ChatBubbleLeftRightIcon",
    },
    {
        name: "FAQ's",
        link: true,
        border: false,
        startWith: "/admin/faq",
        route: "admin.faq.index",
        icon: "QuestionMarkCircleIcon",
    },
    {
        name: "Articles",
        link: true,
        border: false,
        startWith: "/admin/blogs",
        route: "admin.blogs.index",
        icon: "DocumentPlusIcon",
    },
    {
        name: "Contact Us",
        link: true,
        border: false,
        startWith: "/admin/contact-us",
        route: "admin.contact-us.index",
        icon: "PhoneIcon",
    },
    //bookings
    {
        name: "Bookings",
        link: true,
        border: false,
        startWith: "/admin/bookings",
        route: "admin.bookings.index",
        icon: "CalendarIcon",
    },
    //news letter subscribers
    {
        name: "NewsLetter Subscribers",
        link: true,
        border: false,
        startWith: "/admin/news-letter-subscribers",
        route: "admin.news-letter-subscribers.index",
        icon: "EnvelopeIcon",
    },

    { name: "Template", link: false, border: true },
    {
        name: "Home Hero",
        link: true,
        border: false,
        startWith: "/admin/home-heros",
        route: "admin.home-heros.index",
        icon: "AdjustmentsHorizontalIcon",
    },

];
